<?php

use dmstr\bootstrap\Tabs;
use dmstr\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
* @var yii\web\View $this
* @var common\models\TourInfo $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'TourInfo');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'TourInfos'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud tour-info-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('app', 'TourInfo') ?>        <small>
            <?= $model->name ?>        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'),
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('app', 'Copy'),
            ['create', 'id' => $model->id, 'TourInfo'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'),
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . Yii::t('app', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('common\models\TourInfo'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            'id',
        'name:ntext',
        'date_begin',
        'date_end',
        'days',
        'active:boolean',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'hotels_info_id',
    'value' => ($model->getHotelsInfo()->one() ? Html::a($model->getHotelsInfo()->one()->name, ['hotels-info/view', 'id' => $model->getHotelsInfo()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>



    <?php /*$this->beginBlock('SalBaskets'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' ' . Yii::t('app', 'Sal Baskets'),
            ['sal-basket/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' ' . Yii::t('app', 'Sal Basket'),
            ['sal-basket/create', 'SalBasket' => ['tour_info_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-SalBaskets', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-SalBaskets ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getSalBaskets(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-salbaskets']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel'  => Yii::t('app', 'Last')
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'sal-basket' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'sal-basket'
],
        'id',
        'date',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'userinfo_id',
    'value' => function ($model) {
        if ($rel = $model->getUserinfo()->one()) {
            return Html::a($rel->id, ['userinfo/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'hotels_info_id',
    'value' => function ($model) {
        if ($rel = $model->getHotelsInfo()->one()) {
            return Html::a($rel->name, ['hotels-info/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'trans_info_id',
    'value' => function ($model) {
        if ($rel = $model->getTransInfo()->one()) {
            return Html::a($rel->name, ['trans-info/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'price',
        'col_day',
        'col_person',
        'col_kids',
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() */ ?>


<?php $this->beginBlock('SalOrders'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
      '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' ' . Yii::t('app', 'Sal Orders'),
            ['sal-order/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
      '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' ' . Yii::t('app', 'Sal Order'),
            ['sal-order/create', 'SalOrder' => ['tour_info_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-SalOrders', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-SalOrders ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getSalOrders(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-salorders']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel'  => Yii::t('app', 'Last')
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'sal-order' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'sal-order'
],
        'id',
        'date',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'sal_order_status_id',
    'value' => function ($model) {
        if ($rel = $model->getSalOrderStatus()->one()) {
            return Html::a($rel->name, ['sal-order-status/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'date_begin',
        'date_end',
        'enable:boolean',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
        [
            'class' => yii\grid\DataColumn::className(),
            'attribute' => 'hotels_info_id',
            'value' => function ($model) {
                if ($rel = $model->getHotelsInfo()->one()) {
                    return Html::a($rel->name, ['hotels-info/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                } else {
                    return '';
                }
            },
            'format' => 'raw',
        ],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
        [
            'class' => yii\grid\DataColumn::className(),
            'attribute' => 'hotels_appartment_id',
            'value' => function ($model) {
                if ($rel = $model->getHotelsAppartment()->one()) {
                    return Html::a($rel->name, ['hotels-appartment/view', 'id' => $rel->id, 'hotels_info_id' => $rel->hotels_info_id,], ['data-pjax' => 0]);
                } else {
                    return '';
                }
            },
            'format' => 'raw',
        ],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
        [
            'class' => yii\grid\DataColumn::className(),
            'attribute' => 'trans_info_id',
            'value' => function ($model) {
                if ($rel = $model->getTransInfo()->one()) {
                    return Html::a($rel->name, ['tour-type-transport/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                } else {
                    return '';
                }
            },
            'format' => 'raw',
        ],
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('TourTypes'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
      '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' ' . Yii::t('app', 'Tour Types'),
            ['tour-type/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
      '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' ' . Yii::t('app', 'Tour Type'),
            ['tour-type/create', 'TourType' => ['id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
  <?= Html::a(
      '<span class="glyphicon glyphicon-link"></span> ' . Yii::t('app', 'Attach') . ' ' . Yii::t('app', 'Tour Type'), ['tour-info-has-tour-type/create', 'TourInfoHasTourType' => ['tour_info_id' => $model->id]],
            ['class'=>'btn btn-info btn-xs']
        ) ?>
</div></div><?php Pjax::begin(['id'=>'pjax-TourTypes', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-TourTypes ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getTourInfoHasTourTypes(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-tourinfohastourtypes']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel'  => Yii::t('app', 'Last')
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {delete}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'tour-info-has-tour-type' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        'delete' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, [
                    'class' => 'text-danger',
                    'title'         => Yii::t('app', 'Remove'),
                    'data-confirm'  => Yii::t('app', 'Are you sure you want to delete the related item?'),
                    'data-method' => 'post',
                    'data-pjax' => '0',
                ]);
            },
'view' => function ($url, $model) {
                return Html::a(
                    '<span class="glyphicon glyphicon-cog"></span>',
                    $url,
                    [
                        'data-title'  => Yii::t('app', 'View Pivot Record'),
                        'data-toggle' => 'tooltip',
                        'data-pjax'   => '0',
                        'class'       => 'text-muted',
                    ]
                );
            },
    ],
    'controller' => 'tour-info-has-tour-type'
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'tour_type_id',
    'value' => function ($model) {
        if ($rel = $model->getTourType()->one()) {
            return Html::a($rel->name, ['tour-type/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('TourTypeTransports'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
      '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' ' . Yii::t('app', 'Tour Type Transports'),
            ['tour-type-transport/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
      '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' ' . Yii::t('app', 'Tour Type Transport'),
            ['tour-type-transport/create', 'TourTypeTransport' => ['id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
  <?= Html::a(
      '<span class="glyphicon glyphicon-link"></span> ' . Yii::t('app', 'Attach') . ' ' . Yii::t('app', 'Tour Type Transport'), ['tour-info-has-tour-type-transport/create', 'TourInfoHasTourTypeTransport' => ['tour_info_id' => $model->id]],
            ['class'=>'btn btn-info btn-xs']
        ) ?>
</div></div><?php Pjax::begin(['id'=>'pjax-TourTypeTransports', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-TourTypeTransports ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getTourInfoHasTourTypeTransports(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-tourinfohastourtypetransports']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel'  => Yii::t('app', 'Last')
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {delete}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'tour-info-has-tour-type-transport' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        'delete' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, [
                    'class' => 'text-danger',
                    'title'         => Yii::t('app', 'Remove'),
                    'data-confirm'  => Yii::t('app', 'Are you sure you want to delete the related item?'),
                    'data-method' => 'post',
                    'data-pjax' => '0',
                ]);
            },
'view' => function ($url, $model) {
                return Html::a(
                    '<span class="glyphicon glyphicon-cog"></span>',
                    $url,
                    [
                        'data-title'  => Yii::t('app', 'View Pivot Record'),
                        'data-toggle' => 'tooltip',
                        'data-pjax'   => '0',
                        'class'       => 'text-muted',
                    ]
                );
            },
    ],
    'controller' => 'tour-info-has-tour-type-transport'
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'tour_type_transport_id',
    'value' => function ($model) {
        if ($rel = $model->getTourTypeTransport()->one()) {
            return Html::a($rel->name, ['tour-type-transport/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('TourPrices'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
      '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' ' . Yii::t('app', 'Tour Prices'),
            ['tour-price/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
      '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' ' . Yii::t('app', 'Tour Price'),
            ['tour-price/create', 'TourPrice' => ['tour_info_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-TourPrices', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-TourPrices ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getTourPrices(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-tourprices']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel'  => Yii::t('app', 'Last')
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'tour-price' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'tour-price'
],
        'id',
        'price',
        'date',
        'active:boolean',
        'date_begin',
        'date_end',
        'in_hotels',
        'in_trans',
        'in_food',
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['common\models\TourInfo'],
    'active'  => true,
                     ],/*[
    'content' => $this->blocks['SalBaskets'],
    'label'   => '<small>' . Yii::t('app', 'Sal Baskets') .' <span class="badge badge-default">'.count($model->getSalBaskets()->asArray()->all()).'</span></small>',
    'active'  => false,
],*/
                         [
    'content' => $this->blocks['SalOrders'],
                             'label' => '<small>' .
                                 Yii::t('app', 'Sal Orders') . ' <span class="badge badge-default">' . count($model->getSalOrders()->asArray()->all()) . '</span></small>',
    'active'  => false,
],[
    'content' => $this->blocks['TourTypes'],
                             'label' => '<small>' . Yii::t('app', 'Tour Types') . ' <span class="badge badge-default">' . count($model->getTourTypes()->asArray()->all()) . '</span></small>',
    'active'  => false,
],[
    'content' => $this->blocks['TourTypeTransports'],
                             'label' => '<small>' . Yii::t('app', 'Tour Type Transports') . ' <span class="badge badge-default">' . count($model->getTourTypeTransports()->asArray()->all()) . '</span></small>',
    'active'  => false,
],[
    'content' => $this->blocks['TourPrices'],
                             'label' => '<small>' . Yii::t('app', 'Tour Prices') . ' <span class="badge badge-default">' . count($model->getTourPrices()->asArray()->all()) . '</span></small>',
    'active'  => false,
], ]
                 ]
    );
    ?>
</div>
