<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the model class for table "userinfo".
 *
 * @property integer $id
 * @property string $login
 * @property string $email
 * @property string $password
 * @property string $create_time
 * @property string $last_login
 * @property string $auth_key
 * @property integer $user_role_id
 *
 * @property AccessLimitation[] $accessLimitations
 * @property LoginHistory[] $loginHistories
 * @property LoginStatistic[] $loginStatistics
 * @property UserRole $userRole
 */
class Userinfo extends \yii\db\ActiveRecord
{
    const STATUS_BLOCKED = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_WAIT = 2;

    public $password_repeat;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%userinfo}}';
    }

    public function behaviors()
    {
        /*return parent::behaviors(); // TODO: Change the autogenerated stub*/
        return[
            /*[
                'class' => TimestampBehavior::className(),
            ],*/
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'create_time',
                'updatedAtAttribute' => 'last_login',
                'value' => new Expression('NOW()'),
                /*function () {
                    return date('Y-m-d H:i:s');
                }*/
            ],
        ];
    }

    public function scenarios()
    {
        /*return parent::scenarios(); // TODO: Change the autogenerated stub*/
        return [
            'login' => ['login','password'],
            'register' => ['login','email','password'],
        ];
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['login', 'password', 'password_repeat', 'user_role_id'], 'required'],
            /*[['create_time', 'last_login'], 'safe'],*/
            [['user_role_id'], 'integer'],
            [['login'], 'string', 'max' => 50],
            [['email'], 'unique'],
            [['email'], 'string', 'max' => 200],
            /*[['password'], 'compare'],
            [['password'], 'string', 'max' => 32],
            [['password_repeat'], 'safe'],*/
            [['password_repeat'], 'compare', 'compareAttribute' => 'password'],
            /*[['auth_key'], 'string', 'max' => 250],*/
            [['login'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'login' => 'Логин',
            'email' => 'Email',
            'password' => 'Пароль',
            'password_repeat' => 'Повторите пароль',
            'create_time' => 'Время создания пользователя',
            'last_login' => 'Время последнего входа',
            'auth_key' => 'Ключ авторизации',
            'user_role_id' => 'User Role ID',
        ];
    }

    public function getStatusName()
    {
        return ArrayHelper::getValue(self::getStatusesArray(),$this->status);
    }

    public function getStatusesArray()
    {
        return[
            self::STATUS_BLOCKED => 'Заблокирован',
            self::STATUS_ACTIVE => 'Активен',
            self::STATUS_WAIT => 'Ожидает подтверждения',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccessLimitations()
    {
        return $this->hasMany(AccessLimitation::className(), ['userinfo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoginHistories()
    {
        return $this->hasMany(LoginHistory::className(), ['userinfo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoginStatistics()
    {
        return $this->hasMany(LoginStatistic::className(), ['userinfo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserRole()
    {
        return $this->hasOne(UserRole::className(), ['id' => 'user_role_id']);
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->auth_key === $authKey;
    }

    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString(64);
    }


}
