<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "userinfo".
 *
 * @property integer $id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $create_time
 * @property string $last_login
 * @property string $auth_key
 * @property integer $user_role_id
 *
 * @property AccessLimitation[] $accessLimitations
 * @property LoginHistory[] $loginHistories
 * @property LoginStatistic[] $loginStatistics
 * @property UserRole $userRole
 */
class Userinfo extends ActiveRecord implements IdentityInterface
{
    const STATUS_BLOCKED = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_WAIT = 2;

    public $password_repeat;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%userinfo}}';
    }

    public function behaviors()
    {
        /*return parent::behaviors(); // TODO: Change the autogenerated stub*/
        return[
            /*[
                'class' => TimestampBehavior::className(),
            ],*/
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'create_time',
                'updatedAtAttribute' => 'last_login',
                'value' => new Expression('NOW()'),
                /*function () {
                    return date('Y-m-d H:i:s');
                }*/
            ],
        ];
    }

    /*public function scenarios()
    {
        return parent::scenarios(); // TODO: Change the autogenerated stub
        /*return [
            'login' => ['login','password'],
            'register' => ['login','email','password'],
        ];*
    }*/


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password', /*'password_repeat',*/ 'user_role_id'], 'required'],
            /*[['create_time', 'last_login'], 'safe'],*/
            [['user_role_id'], 'integer'],
            [['username'], 'string', 'max' => 50],
            [['email'], 'unique'],
            [['email'],'email'],
            [['email'], 'string', 'max' => 200],
            /*[['password'], 'compare'],
            [['password'], 'string', 'max' => 32],
            [['password_repeat'], 'safe'],
            [['password_repeat'], 'compare', 'compareAttribute' => 'password'],*/
            /*[['auth_key'], 'string', 'max' => 250],*/
            [['username'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Логин',
            'email' => 'Email',
            'password' => 'Пароль',
            'password_repeat' => 'Повторите пароль',
            'create_time' => 'Время создания пользователя',
            'last_login' => 'Время последнего входа',
            'auth_key' => 'Ключ авторизации',
            'user_role_id' => 'User Role ID',
        ];
    }

    public function getStatusName()
    {
        return ArrayHelper::getValue(self::getStatusesArray(),$this->status);
    }

    public function getStatusesArray()
    {
        return[
            self::STATUS_BLOCKED => 'Заблокирован',
            self::STATUS_ACTIVE => 'Активен',
            self::STATUS_WAIT => 'Ожидает подтверждения',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccessLimitations()
    {
        return $this->hasMany(AccessLimitation::className(), ['userinfo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoginHistories()
    {
        return $this->hasMany(LoginHistory::className(), ['userinfo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoginStatistics()
    {
        return $this->hasMany(LoginStatistic::className(), ['userinfo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserRole()
    {
        return $this->hasOne(UserRole::className(), ['id' => 'user_role_id']);
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->auth_key === $authKey;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }

}
