<?php
/**
 * Created by PhpStorm.
 * User: kirsanov_av
 * Date: 02.05.2016
 * Time: 16:33
 */

namespace frontend\widgets\filtertour;

use yii\helpers\Html;
use yii\web\View;
use yii\bootstrap\Widget;
use common\models\HotelsInfo;
use common\models\TourInfo;
use common\models\Country;


class FilterTour extends Widget
{
    public $model;
    public $content;
    protected $_priceMax;
    protected $_priceMin;
    protected $_country;
    protected $_dateMax;
    protected $_dateMin;
    protected $_city;

    public function init()
    {
        parent::init();

        //Подключаема модели тура

        //Формируем css
        $this->content = Html::tag('div', null, ['class' => 'filter',]);
        //Добавляем фильтр
        /*$this->content .= Html::tag('div',)*/
        $div = '<div class="filter">';

    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return Html::encode($this->content);
    }

    //Получаем данные для вывода
    public function getData(){
        
    }
    public function getFilterData(){

        /**
         * Необходимо установить фильтр по следующим параметрам:
         * Страна - country.name
         * Дата: от и до - tour_info.date_begin tour_info.date_end
         * Цена: от и до - tour_price.price
         * Количество дней - tour_info.days
         *
         */
        $query = TourInfo::find()->innerJoin('tour_price','tour_price.tour_info_id = tour_info.id')
            ->innerJoin('hotels_info_has_tour_info', 'hotels_info_has_tour_info.tour_info_id = tour_info.id')
            ->innerJoin('hotels_info', 'hotels_info.id = hotels_info_has_tour_info.hotels_info_id')
            ->innerJoin('country', 'country.id = hotels_info.country')
            ->andFilterWhere('tour_price.price >= '.$this->_priceMin)
            ->andFilterWhere('tour_price.price <= ' . $this->_priceMax)
            ->andFilterWhere('tour_info.date_begin >= ' . $this->_dateMin)
            ->andFilterWhere('tour_info.date_end <=' . $this->_dateMax)
            ->andFilterWhere('UPPER(country.name) LIKE ' . strtoupper($this->_country))
            ->andFilterWhere('UPPER(hotels_info.address) LIKE ' . strtoupper($this->_city));

    }

    public function getPriceMax(){
        /*
         * */
    }
}