<?php
/**
 * Created by PhpStorm.
 * User: kirsanov_av
 * Date: 02.05.2016
 * Time: 16:33
 */

namespace frontend\widgets\filtertour;

use yii\helpers\Html;
use yii\web\View;
use yii\bootstrap\Widget;
use common\models\HotelsInfo;

class FilterTour extends Widget
{
    public $model;
    public $content;

    protected function initForm()
    {

    }

    public function init()
    {
        parent::init();

        //Подключаема модели тура
        
        //Формируем css
        $this->content = Html::tag('div', null, ['class' => 'filter',]);
        //Добавляем фильтр
        /*$this->content .= Html::tag('div',)*/
        $div = '<div class="filter">';

    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return Html::encode($this->content);
    }
}