<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var common\models\HotelsPricing $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'HotelsPricing');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'HotelsPricings'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud hotels-pricing-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('app', 'HotelsPricing') ?>        <small>
            <?= $model->name ?>        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'),
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('app', 'Copy'),
            ['create', 'id' => $model->id, 'HotelsPricing'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'),
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . Yii::t('app', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('common\models\HotelsPricing'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
[
    'format' => 'html',
    'attribute' => 'hotels_appartment_id',
    'value' => ($model->getHotelsAppartment()->one() ? Html::a($model->getHotelsAppartment()->one()->name, ['hotels-appartment/view', 'id' => $model->getHotelsAppartment()->one()->id,'hotels_info_id' => $model->getHotelsAppartment()->one()->hotels_info_id,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'hotels_appartment_hotels_info_id',
    'value' => ($model->getHotelsInfo()->one() ? Html::a($model->getHotelsInfo()->one()->name, ['hotels-info/view', 'id' => $model->getHotelsInfo()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'hotels_type_of_food_id',
    'value' => ($model->getHotelsTypeOfFood()->one() ? Html::a($model->getHotelsTypeOfFood()->one()->name, ['hotels-type-of-food/view', 'id' => $model->getHotelsTypeOfFood()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
        'date',
        'name:ntext',
        'active',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('HotelsPayPeriods'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' Hotels Pay Periods',
            ['hotels-pay-period/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' Hotels Pay Period',
            ['hotels-pay-period/create', 'HotelsPayPeriod' => ['hotels_pricing_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-HotelsPayPeriods', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-HotelsPayPeriods ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getHotelsPayPeriods(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-hotelspayperiods']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('app', 'First'),
        'lastPageLabel'  => Yii::t('app', 'Last')
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'hotels-pay-period' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'hotels-pay-period'
],
        
        'date_begin',
        'date_end',
        'active',
        'price',
        'date_add',
        'date_edit',
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['common\models\HotelsPricing'],
    'active'  => true,
],[
    'content' => $this->blocks['HotelsPayPeriods'],
    'label'   => '<small>' . Yii::t('app','Hotels Pay Periods') .' <span class="badge badge-default">'.count($model->getHotelsPayPeriods()->asArray()->all()).'</span></small>',
    'active'  => false,
], ]
                 ]
    );
    ?>
</div>
