<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use kartik\widgets\FileInput;

/**
 * @var yii\web\View $this
 * @var common\models\HotelsInfo $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="hotels-info-form">

    <?php $form = ActiveForm::begin([
            'id' => 'HotelsInfo',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error',
            'options' => ['enctype' => 'multipart/form-data']
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <?= $form->field($model, 'name')->textInput(['rows' => 6]) ?>
            <?= $form->field($model, 'address')->textarea(['rows' => 6]) ?>
            <?= $form->field($model, 'country')->dropDownList(
                \yii\helpers\ArrayHelper::map(common\models\Country::find()->all(), 'id', 'name'),
                ['prompt' => Yii::t('app', 'Select')]
            ); ?>
            <?= $form->field($model, 'GPS')->textarea(['rows' => 6]) ?>

            <?= $form->field($model, 'links_maps')->textarea(['rows' => 6]) ?>
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'hotels_stars_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(common\models\HotelsStars::find()->all(), 'id', 'name'),
                ['prompt' => Yii::t('app', 'Select')]
            ); ?>

            <?= $form->field($model, 'image')->widget(FileInput::className(),[
                'options' => ['multiple' => true, 'accept' => 'image/*'],
                'pluginOptions' => [
                    'allowedExtensions' => ['jpg','gif','png'],
                    'showUpload' => false,
                    'maxFileCount' => 8,
                ],

            ]); ?>
            <?php /*echo ($model->image) ? Html::img('@web' . \common\models\base\HotelsInfo::IMAGE_PATH . $model->image, ['max-width' => '200px', 'max-height' => '200px']) : null*/ ?>
        </p>
        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [[
                    'label' => $model->getAliasModel(),
                    'content' => $this->blocks['main'],
                    'active' => true,
                ],]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

