<?php

use dmstr\bootstrap\Tabs;
use kartik\widgets\FileInput;
use mirocow\yandexmaps\Canvas as YandexCanvas;
use mirocow\yandexmaps\Map as YandexMap;
use skeeks\yii2\ckeditor\CKEditorPresets;
use skeeks\yii2\ckeditor\CKEditorWidget;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var common\models\HotelsInfo $model
 * @var yii\widgets\ActiveForm $form
 */
$items = $model->getImage2amigos();

    $map = new YandexMap('yandex_map', [
        'center' => [$model->gps_point_m, $model->gps_point_p],

        'zoom' => 10,
        // Enable zoom with mouse scroll
        'behaviors' => array('default'),
        'type' => "yandex#map",
    ],
        [
            // Permit zoom only fro 9 to 11
            'minZoom' => 4,
            'maxZoom' => 18,
            'controls' => [
                /*"new ymaps.control.SmallZoomControl()",*/
                /*"\"smallZoomControl\"",*/
                "new ymaps.control.TypeSelector(['yandex#map', 'yandex#satellite'])",
            ],
            'behaviors' => ['scrollZoom' => 'disable'],
            'events' => [
                'click' => 'function(e) {var coords = e.get(\'coords\');$(\'#hotelsinfo-gps_point_m\').val(coords[0].toPrecision(8));$(\'#hotelsinfo-gps_point_p\').val(coords[1].toPrecision(8));}',

            ]
        ]
    );

/*echo "<pre>";
var_dump($items);
die;*/
/*
if (Yii::$app->controller->action->id === 'update'){
    $imageFiles = $model->getImages();
    foreach ($imageFiles as $image){
        $items[] = [
            'url' => $image->getUrl(),
            'src' => $image->getUrl('120px'),
            'options' => ['title' => Yii::t('app', 'Photo hotels') . ' ' . $model->name],
        ];
    }
}*/


?>

<div class="hotels-info-form">

    <?php $form = ActiveForm::begin([
            'id' => 'HotelsInfo',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error',
            'options' => ['enctype' => 'multipart/form-data']
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <?= $form->field($model, 'name')->textInput() ?>

            <?= $form->field($model, 'active')->checkbox() ?>
            <?= $form->field($model, 'top')->checkbox() ?>

            <?= $form->field($model, 'description')->widget(CKEditorWidget::className(), [
                'options' => ['rows' => 6],
                'preset' => CKEditorPresets::FULL,
            ]) ?>
            
            <?= $form->field($model, 'country')->dropDownList(
                \yii\helpers\ArrayHelper::map(common\models\Country::find()->all(), 'id', 'name'),
                ['prompt' => Yii::t('app', 'Select')]
            ); ?>
            <?= $form->field($model, 'city_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(common\models\City::find()->all(), 'id', 'name'),
                ['prompt' => Yii::t('app', 'Select')]
            ); ?>
            <?= $form->field($model, 'address')->textarea(['rows' => 6]) ?>
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'hotels_stars_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(common\models\HotelsStars::find()->all(), 'id', 'name'),
                ['prompt' => Yii::t('app', 'Select')]
            ); ?>
            <?= $form->field($model, 'discount_child')->checkbox() ?>

            <?= $form->field($model, 'period_day')->textInput() ?>


            <?= $form->field($model, 'gps_point_m')->textInput() ?>
            <?= $form->field($model, 'gps_point_p')->textInput() ?>
            <?= $form->field($model, 'imageFiles[]')->widget(FileInput::className(),[
                'language' => 'ru',
                'options' => ['multiple' => true, 'accept' => 'image/*',],
                'pluginOptions' => [
                    'showRemove' => 'true',
                    'previewFileType' => 'any',
                    'allowedExtensions' => ['jpg','gif','png'],
                    'showUpload' => false,
                    'maxFileCount' => 12,
                    //'uploadUrl' => \yii\helpers\Url::to(['uploads'])
                ],

            ]); ?>

            <?= YandexCanvas::widget([
                'htmlOptions' => [
                    'style' => 'height: 400px; width: 90%;',
                ],
                'map' => $map,
            ])?>
            
            <?= \dosamigos\gallery\Gallery::widget(['items' => $items,
                'options' => [
                    'class' => 'row',
                ],
            ]); ?>

            <?php /*echo ($model->image) ? Html::img('@web' . \common\models\base\HotelsInfo::IMAGE_PATH . $model->image, ['max-width' => '200px', 'max-height' => '200px']) : null*/ ?>
        </p>
        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [[
                    'label' => $model->getAliasModel(),
                    'content' => $this->blocks['main'],
                    'active' => true,
                ],]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

