<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "bus_reservation_has_person".
 *
 * @property integer $bus_reservation_id
 * @property integer $person_id
 * @property string $date_add
 * @property string $date_edit
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $lock
 *
 * @property \common\models\BusReservation $busReservation
 * @property \common\models\Person $person
 * @property string $aliasModel
 */
abstract class BusReservationHasPerson extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bus_reservation_has_person';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bus_reservation_id', 'person_id'], 'required'],
            [['bus_reservation_id', 'person_id', 'created_by', 'updated_by', 'lock'], 'integer'],
            [['date_add', 'date_edit'], 'safe'],
            [['bus_reservation_id'], 'exist', 'skipOnError' => true, 'targetClass' => BusReservation::className(), 'targetAttribute' => ['bus_reservation_id' => 'id']],
            [['person_id'], 'exist', 'skipOnError' => true, 'targetClass' => Person::className(), 'targetAttribute' => ['person_id' => 'id']],
            [['lock'], 'default', 'value' => '0'],
            [['lock'], 'mootensai\components\OptimisticLockValidator']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'bus_reservation_id' => Yii::t('app', 'Bus Reservation ID'),
            'person_id' => Yii::t('app', 'Person ID'),
            'date_add' => Yii::t('app', 'Date Add'),
            'date_edit' => Yii::t('app', 'Date Edit'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'lock' => Yii::t('app', 'Lock'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBusReservation()
    {
        return $this->hasOne(\common\models\BusReservation::className(), ['id' => 'bus_reservation_id'])->inverseOf('busReservationHasPeople');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerson()
    {
        return $this->hasOne(\common\models\Person::className(), ['id' => 'person_id'])->inverseOf('busReservationHasPeople');
    }

    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date_add',
                'updatedAtAttribute' => 'date_edit',
                'value' => new \yii\db\Expression('NOW()'),
            ],
            'blameable' => [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            /*'uuid' => [
                'class' => UUIDBehavior::className(),
                'column' => 'id',
            ],*/
        ];
    }

    /**
     * @inheritdoc
     * @return BusReservationHasPersonQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\BusReservationHasPersonQuery(get_called_class());
    }


}
