<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;


use voskobovich\behaviors\ManyToManyBehavior;
use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "bus_route".
 *
 * @property integer $id
 * @property string $name
 * @property string $date_begin
 * @property string $date_end
 * @property string $date
 *
 * @property \common\models\BusRouteHasBusRoutePoint[] $busRouteHasBusRoutePoints
 * @property \common\models\BusRoutePoint[] $busRoutePoints
 * @property \common\models\BusWay[] $busWays
 * @property string $aliasModel
 */
abstract class BusRoute extends \yii\db\ActiveRecord
{

    public $first_point;
    public $end_point;
    public $position;
    public $date_point_forward;
    public $date_point_reverse;
    public $time_pause;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bus_route';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'BusRoutes');
        }else{
            return Yii::t('app', 'BusRoute');
        }
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date',
                'updatedAtAttribute' => false,
            ],
            [
                'class' => ManyToManyBehavior::className(),
                'relations'=>[
                    'routepoint' =>[
                        'busRoutePoints',
                        'viaTableValues' =>[
                            'first_point' => \common\models\BusRouteHasBusRoutePoint::STATUS_DEACTIVE,
                            'end_point' => \common\models\BusRouteHasBusRoutePoint::STATUS_DEACTIVE,
                            'position'=> 1,
                            'date_point_forward' => function() {
                                return new \yii\db\Expression('NOW()');
                            },
                            'time_pause' => 0,
                            'date_point_reverse' => function() {
                                return new \yii\db\Expression('NOW()');
                            },
                        ]
                    ]
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string'],
            [['date_begin', 'date_end'], 'safe'],
            ['date_end', 'compare', 'compareAttribute'=>'date_begin', 'operator' => '>'],
            [['routepoint'],'each','rule'=>['integer']],
            [['first_point', 'end_point', 'time_pause'],'integer'],
            [['date_point_forward', 'date_point_reverse'], 'safe'],
            ['date_point_reverse', 'compare', 'compareAttribute'=>'date_point_forward', 'operator' => '>'],
            ['date_point_reverse', 'compare', 'compareAttribute'=>'date_end', 'operator' => '<'],
            ['date_point_forward', 'compare', 'compareAttribute'=>'date_begin', 'operator' => '>'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'date' => Yii::t('app', 'Date'),
            'date_begin' => Yii::t('app', 'Date Begin'),
            'date_end' => Yii::t('app', 'Date End'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [

        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBusRouteHasBusRoutePoints()
    {
        return $this->hasMany(\common\models\BusRouteHasBusRoutePoint::className(), ['bus_route_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBusRoutePoints()
    {
        return $this->hasMany(\common\models\BusRoutePoint::className(), ['id' => 'bus_route_point_id'])->viaTable('bus_route_has_bus_route_point', ['bus_route_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBusWays()
    {
        return $this->hasMany(\common\models\BusWay::className(), ['bus_path_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return BusRouteQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\BusRouteQuery(get_called_class());
    }
    
    


}
