<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "bus_scheme_seats".
 *
 * @property integer $id
 * @property string $name
 * @property integer $count
 *
 * @property \common\models\BusInfo[] $busInfos
 * @property \common\models\BusReservation[] $busReservations
 * @property string $aliasModel
 */
abstract class BusSchemeSeats extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bus_scheme_seats';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'BusSchemeSeats');
        }else{
            return Yii::t('app', 'BusSchemeSeats');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['count'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            /*'id' => Yii::t('app', 'id'),*/
            'name' => Yii::t('app', 'Name'),
            'count' => Yii::t('app', 'Count seats'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            /*'id' => Yii::t('app', 'id'),*/
            'name' => Yii::t('app', 'Name'),
            'count' => Yii::t('app', 'Count seats'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBusInfos()
    {
        return $this->hasMany(\common\models\BusInfo::className(), ['bus_scheme_seats_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBusReservations()
    {
        return $this->hasMany(\common\models\BusReservation::className(), ['bus_scheme_seats_id' => 'id']);
    }




}
