<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the base-model class for table "city".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $active
 * @property string $date_add
 * @property string $date_edit
 * @property string $aliasModel
 */
abstract class City extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'city';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date_add',
                'updatedAtAttribute' => 'date_edit',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['active'], 'integer'],
            [['name'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            
            'name' => Yii::t('app', 'Название города'),
            'description' => Yii::t('app', 'Описание'),
            'date_add' => Yii::t('app', 'Дата добавления записи'),
            'date_edit' => Yii::t('app', 'Дата последнего редактирования записи'),
            'active' => Yii::t('app', 'Активность'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'name' => Yii::t('app', 'Название города'),
            'description' => Yii::t('app', 'Описание'),
            'date_add' => Yii::t('app', 'Дата добавления записи'),
            'date_edit' => Yii::t('app', 'Дата последнего редактирования записи'),
            'active' => Yii::t('app', 'Активность'),
        ]);
    }


    
    /**
     * @inheritdoc
     * @return CityQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CityQuery(get_called_class());
    }


}
