<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\HotelsAppartmentItem;
use Yii;

/**
 * This is the base-model class for table "hotels_appartment".
 *
 * @property integer $id
 * @property integer $hotels_info_id
 * @property string $name
 * @property double $price
 * @property integer $type_price
 * @property integer $hotels_appartment_item_id
 * @property string $date_add
 * @property string $date_edit
 *
 * @property \common\models\HotelsAppartmentItem $hotelsAppartmentItem
 * @property \common\models\HotelsInfo $hotelsInfo
 * @property \common\models\HotelsAppartmentHasHotelsTypeOfFood[] $hotelsAppartmentHasHotelsTypeOfFoods
 * @property \common\models\HotelsTypeOfFood[] $hotelsTypeOfFoods
 * @property \common\models\HotelsPricing[] $hotelsPricings
 * @property \common\models\SalOrder[] $salOrders
 * @property string $aliasModel
 */
abstract class HotelsAppartment extends \yii\db\ActiveRecord
{

    public $country;
    const IMAGE_PATH = '/uploads/images/';

    protected $imageFullPath;
    public $imageFiles;
    public $delImages;
    public $mainImage;



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hotels_appartment';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            /*[
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date_add',
                'updatedAtAttribute' => 'date_edit',
            ],*/
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hotels_info_id', 'hotels_appartment_item_id'], 'required'],
            [['hotels_info_id', 'type_price', 'hotels_appartment_item_id', 'country'], 'integer'],
            [['name'], 'string'],
            [['price'], 'number'],
            [['hotels_appartment_item_id'], 'exist', 'skipOnError' => true, 'targetClass' => HotelsAppartmentItem::className(), 'targetAttribute' => ['hotels_appartment_item_id' => 'id']],
            [['hotels_info_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\HotelsInfo::className(), 'targetAttribute' => ['hotels_info_id' => 'id']],
            [['delImages','mainImage'],'boolean'],
            [['imageFiles'], 'file', 'extensions' => 'png, jpg, gif', 'maxFiles' => 12],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [

            'hotels_info_id' => Yii::t('app', 'Hotels Info ID'),
            'name' => Yii::t('app', 'Name'),
            'country' => Yii::t('app', 'Country'),
            'price' => Yii::t('app', 'Price'),
            'type_price' => Yii::t('app', 'Type Price'),
            'hotels_appartment_item_id' => Yii::t('app', 'Hotels Appartment Item ID'),
            'date_add' => Yii::t('app', 'Date Add'),
            'date_edit' => Yii::t('app', 'Date Edit'),
        ];
    }

    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
                'hotels_info_id' => Yii::t('app', 'Выберите гостиницу'),
                'name' => Yii::t('app', 'Name'),
                'country' => Yii::t('app', 'Country'),
                'price' => Yii::t('app', 'Price'),
                'type_price' => Yii::t('app', 'Type Price'),
                'hotels_appartment_item_id' => Yii::t('app', 'Hotels Appartment Item ID'),
                'date_add' => Yii::t('app', 'Date Add'),
                'date_edit' => Yii::t('app', 'Date Edit'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHotelsAppartmentItem()
    {
        return $this->hasOne(\common\models\HotelsAppartmentItem::className(), ['id' => 'hotels_appartment_item_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHotelsInfo()
    {
        return $this->hasOne(\common\models\HotelsInfo::className(), ['id' => 'hotels_info_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCountry()
    {
        $model = $this->getHotelsInfo();
        if ($model->one() != null){
            $this->country = $model->one()->country;
            return \common\models\Country::findOne(['id' => $this->country]);
        }
        else{
            return false;
        }
    }

    /**
     * @return string
     */
    public function getHotelsByCountry($idCountry)
    {
        $model = new \common\models\HotelsInfo();
        //$model->find()->andFilterWhere(['country'=>$idCountry]);
        return $model->findAll(['country'=>$idCountry]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHotelsAppartmentHasHotelsTypeOfFoods()
    {
        return $this->hasMany(\common\models\HotelsAppartmentHasHotelsTypeOfFood::className(), ['id' => 'id', 'hotels_appartment_hotels_info_id' => 'hotels_info_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHotelsTypeOfFoods()
    {
        return $this->hasMany(\common\models\HotelsTypeOfFood::className(), ['id' => 'hotels_type_of_food_id'])->viaTable('hotels_appartment_has_hotels_type_of_food', ['id' => 'id', 'hotels_appartment_hotels_info_id' => 'hotels_info_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHotelsPricings()
    {
        return $this->hasMany(\common\models\HotelsPricing::className(), ['hotels_appartment_id' => 'id', 'hotels_appartment_hotels_info_id' => 'hotels_info_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSalOrders()
    {
        return $this->hasMany(\common\models\SalOrder::className(), ['hotels_appartment_id' => 'id', 'hotels_appartment_hotels_info_id' => 'hotels_info_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\HotelsAppartmentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\HotelsAppartmentQuery(get_called_class());
    }

    public function upload(){

        if ($this->validate('imageFiles')){
            foreach($this->imageFiles as $file){
                $filename = uniqid() . '.' . $file->extension;
                $this->imageFullPath= \Yii::$app->getBasePath() . '/web/uploads/images/' . $filename;
                $file->saveAs($this->imageFullPath);
                $this->attachImage($this->imageFullPath);
            }
            return true;
        }
        else{
            return false;
        }
    }
    
    public function getMinPrice($hotels_id){
        
    }
    
    public function getImage2amigos($modelViews=false){
        $items = array();
        $imageFiles = $this->getImages();
        foreach ($imageFiles as $image){
            if ($modelViews){
                $items[] = [
                    'url' => $image->getUrl(),
                    'src' => $image->getUrl('120px'),
                    'options' => ['title' => Yii::t('app', 'Photo hotels') . ' ' . $this->name],
                ];
            }
            else{
                $items[] = [
                    'url' => $image->getUrl(),
                    'src' => $image->getUrl('120px'),
                    'options' => ['title' => Yii::t('app', 'Photo hotels') . ' ' . $this->name],
                    'id'=>$image->urlAlias,
                    'main' => $image->isMain,
                ];
            }

        }
        return $items;
    }

    /**
     * Функция удаляет картинки по ее urlAlais
     * @param array $imageAlias
     * @return bool
     */
    public function imageDelete($imageAlias = array()){
        //Получаем отмеченные изображения
        try {
            if (is_array($imageAlias) && count($imageAlias) > 0) {
                foreach ($imageAlias as $idImage) {
                    $image = $this->getImageByField('urlAlias', $idImage);
                    $this->removeImage($image);
                }
                return true;
            } else {
                return false;
            }
        }
        catch (\Exception $e){
            $msg = (isset($e->errorInfo[2])) ? $e->errorInfo[2] : $e->getMessage();
            $this->addError('_exception', $msg);
        }
    }

}
