<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

//use common\models\HotelsAppartment;
use common\models\HotelsTypeOfFood;
use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "hotels_appartment_has_hotels_type_of_food".
 *
 * @property integer $id
 * @property integer $hotels_appartment_hotels_info_id
 * @property integer $hotels_type_of_food_id
 * @property string $date_add
 * @property string $date_edit
 *
 * @property \common\models\HotelsAppartment $id0
 * @property \common\models\HotelsTypeOfFood $hotelsTypeOfFood
 * @property string $aliasModel
 */
abstract class HotelsAppartmentHasHotelsTypeOfFood extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hotels_appartment_has_hotels_type_of_food';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date_add',
                'updatedAtAttribute' => 'date_edit',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hotels_appartment_hotels_info_id', 'hotels_type_of_food_id'], 'required'],
            [['hotels_appartment_hotels_info_id', 'hotels_type_of_food_id'], 'integer'],
            [['hotels_appartment_hotels_info_id'], 'exist', 'skipOnError' => true, 'targetClass' => HotelsAppartment::className(), 'targetAttribute' => ['id' => 'id', 'hotels_appartment_hotels_info_id' => 'hotels_info_id']],
            [['hotels_type_of_food_id'], 'exist', 'skipOnError' => true, 'targetClass' => HotelsTypeOfFood::className(), 'targetAttribute' => ['hotels_type_of_food_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'hotels_appartment_hotels_info_id' => Yii::t('app', 'Hotels Appartment Hotels Info ID'),
            'hotels_type_of_food_id' => Yii::t('app', 'Hotels Type Of Food ID'),
            'date_add' => Yii::t('app', 'Date Add'),
            'date_edit' => Yii::t('app', 'Date Edit'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getId0()
    {
        return $this->hasOne(\common\models\HotelsAppartment::className(), ['id' => 'id', 'hotels_info_id' => 'hotels_appartment_hotels_info_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHotelsTypeOfFood()
    {
        return $this->hasOne(\common\models\HotelsTypeOfFood::className(), ['id' => 'hotels_type_of_food_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\HotelsAppartmentHasHotelsTypeOfFoodQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\HotelsAppartmentHasHotelsTypeOfFoodQuery(get_called_class());
    }


}
