<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "kontragent_org".
 *
 * @property integer $id
 *
 * @property \common\models\MmKontragentPersonsHasKontragentOrg[] $mmKontragentPersonsHasKontragentOrgs
 * @property \common\models\KontragentPersons[] $kontragentPersonsIdKontragent-persons
 * @property string $aliasModel
 */
abstract class KontragentOrg extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kontragent_org';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'KontragentOrgs');
        }else{
            return Yii::t('app', 'KontragentOrg');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('app', 'ID'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMmKontragentPersonsHasKontragentOrgs()
    {
        return $this->hasMany(\common\models\MmKontragentPersonsHasKontragentOrg::className(), ['kontragent_org_id_kontragent_org' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKontragentPersonsIdKontragentPersons()
    {
        return $this->hasMany(\common\models\KontragentPersons::className(), ['id' => 'kontragent_persons_id_kontragent-persons'])->viaTable('mm_kontragent_persons_has_kontragent_org', ['kontragent_org_id_kontragent_org' => 'id']);
    }




}
