<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "mm_kontragent_persons_has_kontragent_org".
 *
 * @property integer $kontragent_persons_id_kontragent-persons
 * @property integer $kontragent_org_id_kontragent_org
 *
 * @property \common\models\KontragentOrg $kontragentOrgIdKontragentOrg
 * @property \common\models\KontragentPersons $kontragentPersonsIdKontragent-persons
 * @property string $aliasModel
 */
abstract class MmKontragentPersonsHasKontragentOrg extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mm_kontragent_persons_has_kontragent_org';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'MmKontragentPersonsHasKontragentOrgs');
        }else{
            return Yii::t('app', 'MmKontragentPersonsHasKontragentOrg');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kontragent_persons_id_kontragent-persons', 'kontragent_org_id_kontragent_org'], 'required'],
            [['kontragent_persons_id_kontragent-persons', 'kontragent_org_id_kontragent_org'], 'integer'],
            [['kontragent_org_id_kontragent_org'], 'exist', 'skipOnError' => true, 'targetClass' => KontragentOrg::className(), 'targetAttribute' => ['kontragent_org_id_kontragent_org' => 'id']],
            [['kontragent_persons_id_kontragent-persons'], 'exist', 'skipOnError' => true, 'targetClass' => KontragentPersons::className(), 'targetAttribute' => ['kontragent_persons_id_kontragent-persons' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'kontragent_persons_id_kontragent-persons' => Yii::t('app', 'Kontragent Persons Id Kontragent Persons'),
            'kontragent_org_id_kontragent_org' => Yii::t('app', 'Kontragent Org Id Kontragent Org'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'kontragent_persons_id_kontragent-persons' => Yii::t('app', 'Kontragent Persons Id Kontragent Persons'),
            'kontragent_org_id_kontragent_org' => Yii::t('app', 'Kontragent Org Id Kontragent Org'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKontragentOrgIdKontragentOrg()
    {
        return $this->hasOne(\common\models\KontragentOrg::className(), ['id' => 'kontragent_org_id_kontragent_org']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKontragentPersonsIdKontragentPersons()
    {
        return $this->hasOne(\common\models\KontragentPersons::className(), ['id' => 'kontragent_persons_id_kontragent-persons']);
    }




}
