<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use common\models\TourInfo;

/**
 * This is the base-model class for table "tour_price".
 *
 * @property integer $id
 * @property string $price
 * @property string $date
 * @property integer $active
 * @property string $date_begin
 * @property string $date_end
 * @property integer $tour_info_id
 * @property integer $in_hotels
 * @property integer $in_trans
 * @property integer $in_food
 *
 * @property \common\models\TourInfo $tourInfo
 * @property string $aliasModel
 */
abstract class TourPrice extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tour_price';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'TourPrices');
        }else{
            return Yii::t('app', 'TourPrice');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'price', 'tour_info_id'], 'required'],
            [[ 'active', 'tour_info_id', 'in_hotels', 'in_trans', 'in_food'], 'integer'],
            [['price'], 'number'],
            [['date', 'date_begin', 'date_end'], 'safe'],
            [['tour_info_id'], 'exist', 'skipOnError' => true, 'targetClass' => TourInfo::className(), 'targetAttribute' => ['tour_info_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [

            'price' => Yii::t('app', 'Price'),
            'date' => Yii::t('app', 'Date'),
            'active' => Yii::t('app', 'Active'),
            'date_begin' => Yii::t('app', 'Date Begin'),
            'date_end' => Yii::t('app', 'Date End'),
            'tour_info_id' => Yii::t('app', 'Tour Info ID'),
            'in_hotels' => Yii::t('app', 'In Hotels'),
            'in_trans' => Yii::t('app', 'In Trans'),
            'in_food' => Yii::t('app', 'In Food'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            
            'price' => Yii::t('app', 'Цена услуги/товара'),
            'date' => Yii::t('app', 'Дата создания цены товара'),
            'active' => Yii::t('app', 'Актуальна ли цена?'),
            'date_begin' => Yii::t('app', 'Начало действия цены'),
            'date_end' => Yii::t('app', 'Окончание действия цены'),
            'tour_info_id' => Yii::t('app', 'Тур, для которого актуальна цена'),
            'in_hotels' => Yii::t('app', 'В цену включено проживание'),
            'in_trans' => Yii::t('app', 'В цену включен проезд'),
            'in_food' => Yii::t('app', 'В цену включено питание'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTourInfo()
    {
        return $this->hasOne(TourInfo::className(), ['id' => 'tour_info_id']);
    }




}
