<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\TransInfoQuery;
use Yii;

/**
 * This is the base-model class for table "trans_info".
 *
 * @property integer $id
 * @property integer $trans_type_id
 * @property string $name
 * @property integer $trans_route_id
 * @property integer $seats
 *
 * @property \common\models\SalBasket[] $salBaskets
 * @property \common\models\SalOrder[] $salOrders
 * @property \common\models\TransRoute $transRoute
 * @property \common\models\TransType $transType
 * @property \common\models\TransPrice[] $transPrices
 * @property \common\models\TransReservation[] $transReservations
 * @property string $aliasModel
 */
abstract class TransInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'trans_info';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['trans_type_id', 'name', 'trans_route_id'], 'required'],
            [['trans_type_id', 'trans_route_id', 'seats'], 'integer'],
            [['name'], 'string'],
            [['trans_route_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TransRoute::className(), 'targetAttribute' => ['trans_route_id' => 'id']],
            [['trans_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TransType::className(), 'targetAttribute' => ['trans_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            
            'trans_type_id' => Yii::t('app', 'Trans Type ID'),
            'name' => Yii::t('app', 'Name'),
            'trans_route_id' => Yii::t('app', 'Trans Route ID'),
            'seats' => Yii::t('app', 'Seats'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            
            'trans_type_id' => Yii::t('app', 'Необходимый тип трансопрт'),
            'name' => Yii::t('app', 'Наименование'),
            'seats' => Yii::t('app', 'Количество посадочных мест в транспорте'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSalBaskets()
    {
        return $this->hasMany(\common\models\SalBasket::className(), ['trans_info_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSalOrders()
    {
        return $this->hasMany(\common\models\SalOrder::className(), ['trans_info_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransRoute()
    {
        return $this->hasOne(\common\models\TransRoute::className(), ['id' => 'trans_route_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransType()
    {
        return $this->hasOne(\common\models\TransType::className(), ['id' => 'trans_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransPrices()
    {
        return $this->hasMany(\common\models\TransPrice::className(), ['trans_info_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransReservations()
    {
        return $this->hasMany(\common\models\TransReservation::className(), ['trans_info_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\TransInfoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TransInfoQuery(get_called_class());
    }


}
