<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\TransRouteHasTransStationQuery;
use Yii;

/**
 * This is the base-model class for table "trans_route_has_trans_station".
 *
 * @property integer $trans_route_id
 * @property integer $trans_station_id
 * @property integer $position
 *
 * @property \common\models\TransRoute $transRoute
 * @property \common\models\TransStation $transStation
 * @property string $aliasModel
 */
abstract class TransRouteHasTransStation extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'trans_route_has_trans_station';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['trans_route_id', 'trans_station_id'], 'required'],
            [['trans_route_id', 'trans_station_id', 'position'], 'integer'],
            [['trans_route_id'], 'exist', 'skipOnError' => true, 'targetClass' => TransRoute::className(), 'targetAttribute' => ['trans_route_id' => 'id']],
            [['trans_station_id'], 'exist', 'skipOnError' => true, 'targetClass' => TransStation::className(), 'targetAttribute' => ['trans_station_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'trans_route_id' => Yii::t('app', 'Trans Route ID'),
            'trans_station_id' => Yii::t('app', 'Trans Station ID'),
            'position' => Yii::t('app', 'Position'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransRoute()
    {
        return $this->hasOne(\common\models\TransRoute::className(), ['id' => 'trans_route_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransStation()
    {
        return $this->hasOne(\common\models\TransStation::className(), ['id' => 'trans_station_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\TransRouteHasTransStationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TransRouteHasTransStationQuery(get_called_class());
    }


}
