<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\TransTypeQuery;
use Yii;

/**
 * This is the base-model class for table "trans_type".
 *
 * @property integer $id
 * @property string $name
 * @property integer $trans_type_station_id
 *
 * @property \common\models\TransInfo[] $transInfos
 * @property \common\models\TransTypeStation $transTypeStation
 * @property string $aliasModel
 */
abstract class TransType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'trans_type';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'trans_type_station_id'], 'required'],
            [['name'], 'string'],
            [['trans_type_station_id'], 'integer'],
            [['trans_type_station_id'], 'exist', 'skipOnError' => true, 'targetClass' => TransTypeStation::className(), 'targetAttribute' => ['trans_type_station_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            
            'name' => Yii::t('app', 'Name'),
            'trans_type_station_id' => Yii::t('app', 'Trans Type Station ID'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            
            'name' => Yii::t('app', 'Название'),
            'trans_type_station_id' => Yii::t('app', 'Выберите тип вокзала для текущего транспорта.'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransInfos()
    {
        return $this->hasMany(\common\models\TransInfo::className(), ['trans_type_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransTypeStation()
    {
        return $this->hasOne(\common\models\TransTypeStation::className(), ['id' => 'trans_type_station_id']);
    }


    
    /**
     * @inheritdoc
     * @return TransTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TransTypeQuery(get_called_class());
    }


}
