<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\TransReservationQuery;
use Yii;

/**
 * This is the base-model class for table "trans_reservation".
 *
 * @property integer $id
 * @property string $name
 * @property string $date_begin
 * @property string $date_end
 * @property integer $number_seats
 * @property integer $persons
 * @property integer $status
 * @property string $date_add
 * @property integer $trans_info_id
 *
 * @property \common\models\TransInfo $transInfo
 * @property string $aliasModel
 */
abstract class TransReservation extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'trans_reservation';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'trans_info_id'], 'required'],
            [['date_begin', 'date_end', 'date_add'], 'safe'],
            ['date_end', 'compare', 'compareAttribute'=>'date_begin', 'operator' => '>'],
            [['number_seats', 'persons', 'status', 'trans_info_id'], 'integer'],
            [['name'], 'string', 'max' => 45],
            [['trans_info_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TransInfo::className(), 'targetAttribute' => ['trans_info_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('app', 'Name'),
            'date_begin' => Yii::t('app', 'Date Begin'),
            'date_end' => Yii::t('app', 'Date End'),
            'number_seats' => Yii::t('app', 'Number Seats'),
            'persons' => Yii::t('app', 'Persons'),
            'status' => Yii::t('app', 'Status'),
            'date_add' => Yii::t('app', 'Date Add'),
            'trans_info_id' => Yii::t('app', 'Trans Info ID'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'name' => Yii::t('app', 'Название'),
            'date_begin' => Yii::t('app', 'Дата начала резервирования (время отъезда).'),
            'date_end' => Yii::t('app', 'Дата окончания резервирования (время приезда).'),
            'number_seats' => Yii::t('app', 'Номер забронированного места'),
            'persons' => Yii::t('app', 'Информация о пассажире'),
            'status' => Yii::t('app', 'Статус резервации'),
            'date_add' => Yii::t('app', 'Дата добавления резерва'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransInfo()
    {
        return $this->hasOne(\common\models\TransInfo::className(), ['id' => 'trans_info_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\TransReservationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TransReservationQuery(get_called_class());
    }


}
