<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\TransTypeStationQuery;
use Yii;

/**
 * This is the base-model class for table "trans_type_station".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \common\models\TransStation[] $transStations
 * @property \common\models\TransType[] $transTypes
 * @property string $aliasModel
 */
abstract class TransTypeStation extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'trans_type_station';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('app', 'Name'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'name' => Yii::t('app', 'Название'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransStations()
    {
        return $this->hasMany(\common\models\TransStation::className(), ['trans_type_station_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransTypes()
    {
        return $this->hasMany(\common\models\TransType::className(), ['trans_type_station_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return TransTypeStationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TransTypeStationQuery(get_called_class());
    }


}
