<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\TransStationQuery;
use Yii;

/**
 * This is the base-model class for table "trans_station".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $gps_parallel
 * @property string $gps_meridian
 * @property integer $address_id
 * @property integer $trans_type_station_id
 *
 * @property \common\models\TransRouteHasTransStation[] $transRouteHasTransStations
 * @property \common\models\TransRoute[] $transRoutes
 * @property \common\models\TransTypeStation $transTypeStation
 * @property string $aliasModel
 */
abstract class TransStation extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'trans_station';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'trans_type_station_id'], 'required'],
            [['name', 'description', 'gps_parallel', 'gps_meridian'], 'string'],
            [['address_id', 'trans_type_station_id'], 'integer'],
            [['trans_type_station_id'], 'exist', 'skipOnError' => true, 'targetClass' => TransTypeStation::className(), 'targetAttribute' => ['trans_type_station_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            'gps_parallel' => Yii::t('app', 'Gps Parallel'),
            'gps_meridian' => Yii::t('app', 'Gps Meridian'),
            'address_id' => Yii::t('app', 'Address ID'),
            'trans_type_station_id' => Yii::t('app', 'Trans Type Station ID'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            'gps_parallel' => Yii::t('app', 'Gps Parallel'),
            'gps_meridian' => Yii::t('app', 'Gps Meridian'),
            'address_id' => Yii::t('app', 'Address ID'),
            'trans_type_station_id' => Yii::t('app', 'Trans Type Station ID'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransRouteHasTransStations()
    {
        return $this->hasMany(\common\models\TransRouteHasTransStation::className(), ['trans_station_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransRoutes()
    {
        return $this->hasMany(\common\models\TransRoute::className(), ['id' => 'trans_route_id'])->viaTable('trans_route_has_trans_station', ['trans_station_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransTypeStation()
    {
        return $this->hasOne(\common\models\TransTypeStation::className(), ['id' => 'trans_type_station_id']);
    }


    
    /**
     * @inheritdoc
     * @return TransStationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TransStationQuery(get_called_class());
    }


}
