<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\TransPriceQuery;
use Yii;

/**
 * This is the base-model class for table "trans_price".
 *
 * @property integer $id
 * @property double $price
 * @property string $date_add
 * @property string $date_edit
 * @property integer $trans_price_type_id
 * @property integer $trans_info_id
 *
 * @property \common\models\TransInfo $transInfo
 * @property \common\models\TransPriceType $transPriceType
 * @property string $aliasModel
 */
abstract class TransPrice extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'trans_price';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['price'], 'number'],
            [['date_add', 'date_edit'], 'safe'],
            [['trans_price_type_id', 'trans_info_id'], 'required'],
            [['trans_price_type_id', 'trans_info_id'], 'integer'],
            [['trans_info_id'], 'exist', 'skipOnError' => true, 'targetClass' => TransInfo::className(), 'targetAttribute' => ['trans_info_id' => 'id']],
            [['trans_price_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => TransPriceType::className(), 'targetAttribute' => ['trans_price_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'price' => Yii::t('app', 'Price'),
            'date_add' => Yii::t('app', 'Date Add'),
            'date_edit' => Yii::t('app', 'Date Edit'),
            'trans_price_type_id' => Yii::t('app', 'Trans Price Type ID'),
            'trans_info_id' => Yii::t('app', 'Trans Info ID'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'price' => Yii::t('app', 'Price'),
            'date_add' => Yii::t('app', 'Date Add'),
            'date_edit' => Yii::t('app', 'Date Edit'),
            'trans_price_type_id' => Yii::t('app', 'Trans Price Type ID'),
            'trans_info_id' => Yii::t('app', 'Trans Info ID'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransInfo()
    {
        return $this->hasOne(\common\models\TransInfo::className(), ['id' => 'trans_info_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransPriceType()
    {
        return $this->hasOne(\common\models\TransPriceType::className(), ['id' => 'trans_price_type_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\TransPriceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TransPriceQuery(get_called_class());
    }


}
