<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
* @var yii\web\View $this
* @var frontend\models\SearchHotelsInfo $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="hotels-info-search">
    <div class="container-fluid">
    <?php $form = ActiveForm::begin([
    'action' => ['/hotels'],
    'method' => 'POST',
    ]); ?>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'tour_type')->dropDownList(
                    \yii\helpers\ArrayHelper::map(common\models\TourType::find()->all(), 'id', 'name'),
                    ['prompt' => Yii::t('app', 'Select')]
                ); ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'country') ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'address') ?>
            </div>
            <div class="col-md-6">
                <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'hotels_stars_id')->dropDownList(
                    \yii\helpers\ArrayHelper::map(common\models\HotelsStars::find()->all(), 'id', 'name'),
                    ['prompt' => Yii::t('app', 'Select')]
                ); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'price_from') ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'price_to') ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'count_tourist') ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'child') ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'date_beg')->widget(\kartik\widgets\DatePicker::className(),[
                    'type'=>\kartik\widgets\DatePicker::TYPE_INPUT,
                ])?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'date_end')->widget(\kartik\widgets\DatePicker::className(),[
                    'type'=>\kartik\widgets\DatePicker::TYPE_INPUT,
                ])?>
            </div>
        </div>

		<?php // echo $form->field($model, 'links_maps') ?>


    <div class="row">

        <div class="text-center form-group">
            <?= Html::submitButton(Yii::t('app', 'Search tour'), ['class' => 'btn btn-primary']) ?>
            <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
        </div>

    </div>

    <?php ActiveForm::end(); ?>
</div>
</div>
