<?php

use dmstr\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var yii\web\View $this
 * @var common\models\HotelsInfo $model
 */
$copyParams = $model->attributes;

$this->title = $model->getAliasModel() . $model->name;
$this->params['breadcrumbs'][] = ['label' => $model->getAliasModel(true), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
$items = $model->getImage2amigos(true);
?>
<div class="giiant-crud hotels-info-view panel panel-info">

    <h1>
        <?= $model->getAliasModel() ?>
        <strong>
            "<?= $model->name ?>"        </strong>
    </h1>


    <div class="clearfix">

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                [
                    'format'=>'html',
                    'attribute' => 'Изображение',
                    'value'=> Html::img($model->getImage()->getUrl('120x'),['alt' => $model->name])
                ],
                'name:ntext',
                [
                    'format'=> 'html',
                    'attribute'=>'description',
                ],
                'address',
                [
                    'format' => 'html',
                    'attribute' => 'country',
                    'value' => ($model->getCountry()->one() ?
                        Html::tag('div',$model->getCountry()->one()->name) :
                        '<span class="label label-warning">?</span>'),
                ],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                [
                    'format' => 'html',
                    'attribute' => 'hotels_stars_id',
                    'value' => ($model->getHotelsStars()->one() ? Html::tag('div', $model->getHotelsStars()->one()->name) : '<span class="label label-warning">?</span>'),
                ],
            ],
        ]); ?>

        <div class="characters table">
            <label>Подробные характеристики</label>
            <table class="table table-striped table-bordered table-hover table-condensed">
                <thead>
                <tr>
                    <th>
                        Характеристика
                    </th>
                    <th>
                        Значение
                    </th>
                </tr>
                </thead>

                <tbody>
                <?= \yii\widgets\ListView::widget([
                    'dataProvider' => $dateProviderCharacters,
                    'itemView' => '_details_character',
                    'summary' => '',
                ]); ?>
                </tbody>
            </table>
        </div>

        <?= \dosamigos\gallery\Gallery::widget(['items' => $items,
            'options' => [
                //'class' => 'row',
            ],
        ]); ?>
    </div>
